checkpoints_refs_cats_run_name:
        r0:
                bicycle: 01-28_12-19-55_CO3D_NeMo_uni6d_sphere500_app0_bicycle_r0_slurm
                bus: 01-28_09-01-43_CO3D_NeMo_uni6d_sphere500_app0_bus_r0_slurm
                car: 01-28_12-08-07_CO3D_NeMo_uni6d_sphere500_app0_car_r0_slurm
                chair: 01-28_12-08-52_CO3D_NeMo_uni6d_sphere500_app0_chair_r0_slurm
                couch: 01-28_12-09-29_CO3D_NeMo_uni6d_sphere500_app0_couch_r0_slurm
                motorcycle: 01-28_12-20-35_CO3D_NeMo_uni6d_sphere500_app0_motorcycle_r0_slurm
                tv: 01-28_09-03-11_CO3D_NeMo_uni6d_sphere500_app0_tv_r0_slurm
        r1:
                bicycle: 01-28_12-09-37_CO3D_NeMo_uni6d_sphere500_app0_bicycle_r1_slurm
                bus: 01-28_09-01-13_CO3D_NeMo_uni6d_sphere500_app0_bus_r1_slurm
                car: 01-28_12-07-37_CO3D_NeMo_uni6d_sphere500_app0_car_r1_slurm
                chair: 01-28_12-08-22_CO3D_NeMo_uni6d_sphere500_app0_chair_r1_slurm
                couch: 01-28_12-09-00_CO3D_NeMo_uni6d_sphere500_app0_couch_r1_slurm
                motorcycle: 01-28_12-20-03_CO3D_NeMo_uni6d_sphere500_app0_motorcycle_r1_slurm
                tv: 01-28_12-08-14_CO3D_NeMo_uni6d_sphere500_app0_tv_r1_slurm
        r2:
                bicycle: 01-28_09-05-02_CO3D_NeMo_uni6d_sphere500_app0_bicycle_r2_slurm
                bus: 01-28_09-01-35_CO3D_NeMo_uni6d_sphere500_app0_bus_r2_slurm
                car: 01-28_12-07-59_CO3D_NeMo_uni6d_sphere500_app0_car_r2_slurm
                chair: 01-28_12-08-45_CO3D_NeMo_uni6d_sphere500_app0_chair_r2_slurm
                couch: 01-28_13-31-24_CO3D_NeMo_uni6d_sphere500_app0_couch_r2_slurm
                motorcycle: 01-29_09-03-15_CO3D_NeMo_uni6d_sphere500_app0_motorcycle_r2_slurm
                tv: 01-28_09-03-04_CO3D_NeMo_uni6d_sphere500_app0_tv_r2_slurm
        r3:
                bicycle: 01-28_09-04-46_CO3D_NeMo_uni6d_sphere500_app0_bicycle_r3_slurm
                bus: 01-28_12-07-30_CO3D_NeMo_uni6d_sphere500_app0_bus_r3_slurm
                car: 01-28_12-07-44_CO3D_NeMo_uni6d_sphere500_app0_car_r3_slurm
                chair: 01-29_09-02-54_CO3D_NeMo_uni6d_sphere500_app0_chair_r3_slurm
                couch: 01-28_12-09-07_CO3D_NeMo_uni6d_sphere500_app0_couch_r3_slurm
                motorcycle: 01-28_12-20-11_CO3D_NeMo_uni6d_sphere500_app0_motorcycle_r3_slurm
                tv: 01-28_09-02-43_CO3D_NeMo_uni6d_sphere500_app0_tv_r3_slurm
        r4:
                bicycle: 01-28_12-09-44_CO3D_NeMo_uni6d_sphere500_app0_bicycle_r4_slurm
                bus: 01-28_09-01-28_CO3D_NeMo_uni6d_sphere500_app0_bus_r4_slurm
                car: 01-28_12-07-51_CO3D_NeMo_uni6d_sphere500_app0_car_r4_slurm
                chair: 01-28_12-08-38_CO3D_NeMo_uni6d_sphere500_app0_chair_r4_slurm
                couch: 01-29_09-03-01_CO3D_NeMo_uni6d_sphere500_app0_couch_r4_slurm
                motorcycle: 01-29_09-03-08_CO3D_NeMo_uni6d_sphere500_app0_motorcycle_r4_slurm
                tv: 01-28_09-02-51_CO3D_NeMo_uni6d_sphere500_app0_tv_r4_slurm
