# @package _global_

checkpoint: ${checkpoint_opt}

checkpoints_refs_cats_run_name:
        r0:
                airplane: 01-25_13-46-49_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_airplane_r0_sphere500_cat_slurm
                bicycle: 01-25_16-13-50_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_bicycle_r0_sphere500_cat_slurm
                bottle: 01-25_21-41-53_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_bottle_r0_sphere500_cat_slurm
                bus: 01-25_17-43-44_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_bus_r0_sphere500_cat_slurm
                car: 01-25_16-11-37_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_car_r0_sphere500_cat_slurm
                chair: 01-25_14-58-46_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_chair_r0_sphere500_cat_slurm
                couch: 01-25_16-13-20_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_couch_r0_sphere500_cat_slurm
                motorcycle: 01-25_18-07-04_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_motorcycle_r0_sphere500_cat_slurm
                train: 01-25_18-05-57_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_train_r0_sphere500_cat_slurm
                tv: 01-25_09-49-30_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_tv_r0_sphere500_cat_slurm
        r1:
                airplane: 01-25_14-57-40_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_airplane_r1_sphere500_cat_slurm
                bicycle: 01-25_16-13-28_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_bicycle_r1_sphere500_cat_slurm
                bottle: 01-25_14-12-36_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_bottle_r1_sphere500_cat_slurm
                bus: 01-25_14-10-54_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_bus_r1_sphere500_cat_slurm
                car: 01-25_09-48-25_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_car_r1_sphere500_cat_slurm
                chair: 01-25_14-35-12_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_chair_r1_sphere500_cat_slurm
                couch: 01-25_17-20-34_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_couch_r1_sphere500_cat_slurm
                motorcycle: 01-25_16-13-57_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_motorcycle_r1_sphere500_cat_slurm
                train: 01-25_18-05-42_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_train_r1_sphere500_cat_slurm
                tv: 01-25_16-11-45_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_tv_r1_sphere500_cat_slurm
        r2:
                airplane: 01-25_14-34-02_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_airplane_r2_sphere500_cat_slurm
                bicycle: 01-25_16-13-42_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_bicycle_r2_sphere500_cat_slurm
                bottle: 01-25_21-41-45_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_bottle_r2_sphere500_cat_slurm
                bus: 01-25_14-33-33_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_bus_r2_sphere500_cat_slurm
                car: 01-25_16-11-30_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_car_r2_sphere500_cat_slurm
                chair: 01-25_09-50-35_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_chair_r2_sphere500_cat_slurm
                couch: 01-26_01-14-48_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_couch_r2_sphere500_cat_slurm
                motorcycle: 01-25_18-06-56_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_motorcycle_r2_sphere500_cat_slurm
                train: 01-25_14-35-56_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_train_r2_sphere500_cat_slurm
                tv: 01-25_09-49-23_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_tv_r2_sphere500_cat_slurm
        r3:
                airplane: 01-25_13-46-27_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_airplane_r3_sphere500_cat_slurm
                bicycle: 01-25_21-42-22_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_bicycle_r3_sphere500_cat_slurm
                bottle: 01-25_21-11-43_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_bottle_r3_sphere500_cat_slurm
                bus: 01-25_15-57-18_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_bus_r3_sphere500_cat_slurm
                car: 01-25_09-48-32_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_car_r3_sphere500_cat_slurm
                chair: 01-25_14-58-39_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_chair_r3_sphere500_cat_slurm
                couch: 01-25_21-42-07_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_couch_r3_sphere500_cat_slurm
                motorcycle: 01-25_21-42-30_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_motorcycle_r3_sphere500_cat_slurm
                train: 01-26_10-04-32_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_train_r3_sphere500_cat_slurm
                tv: 01-25_10-58-41_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_tv_r3_sphere500_cat_slurm
        r4:
                airplane: 01-25_14-33-55_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_airplane_r4_sphere500_cat_slurm
                bicycle: 01-25_13-25-17_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_bicycle_r4_sphere500_cat_slurm
                bottle: 01-25_21-41-38_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_bottle_r4_sphere500_cat_slurm
                bus: 01-25_15-57-26_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_bus_r4_sphere500_cat_slurm
                car: 01-25_14-34-09_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_car_r4_sphere500_cat_slurm
                chair: 01-25_09-50-27_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_chair_r4_sphere500_cat_slurm
                couch: 01-25_21-42-15_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_couch_r4_sphere500_cat_slurm
                motorcycle: 01-25_18-06-43_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_motorcycle_r4_sphere500_cat_slurm
                train: 01-25_21-42-00_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_train_r4_sphere500_cat_slurm
                tv: 01-25_14-12-29_CO3D_NeMo_uni6d_icosphere500_inst_def6d_coord_conv4_tv_r4_sphere500_cat_slurm
