# @package _global_

checkpoint: ${checkpoint_opt}

checkpoints_refs_cats_run_name:
  r0:
    bicycle:
    truck:
    train:
    teddybear:
    car:
    bus:
    motorcycle:
    keyboard:
    handbag:
    remote:
    airplane:
    toilet:
    hairdryer:
    mouse:
    toaster:
    hydrant:
    chair:
    laptop:
    book:
    backpack:
    cellphone: # from cellphone on, no zsp categories
    microwave:
    bench:
    bottle:
    couch:
    cup:
    suitcase:
    tv:
  r1:
    bicycle:
    truck:
    train:
    teddybear:
    car:
    bus:
    motorcycle:
    keyboard:
    handbag:
    remote:
    airplane:
    toilet:
    hairdryer:
    mouse:
    toaster:
    hydrant:
    chair:
    laptop:
    book:
    backpack:
    cellphone: # from cellphone on, no zsp categories
    microwave:
    bench:
    bottle:
    couch:
    cup:
    suitcase:
    tv:
  r2:
    bicycle:
    truck:
    train:
    teddybear:
    car:
    bus:
    motorcycle:
    keyboard:
    handbag:
    remote:
    airplane:
    toilet:
    hairdryer:
    mouse:
    toaster:
    hydrant:
    chair:
    laptop:
    book:
    backpack:
    cellphone: # from cellphone on, no zsp categories
    microwave:
    bench:
    bottle:
    couch:
    cup:
    suitcase:
    tv:
  r3:
    bicycle:
    truck:
    train:
    teddybear:
    car:
    bus:
    motorcycle:
    keyboard:
    handbag:
    remote:
    airplane:
    toilet:
    hairdryer:
    mouse:
    toaster:
    hydrant:
    chair:
    laptop:
    book:
    backpack:
    cellphone: # from cellphone on, no zsp categories
    microwave:
    bench:
    bottle:
    couch:
    cup:
    suitcase:
    tv:
  r4:
    bicycle:
    truck:
    train:
    teddybear:
    car:
    bus:
    motorcycle:
    keyboard:
    handbag:
    remote:
    airplane:
    toilet:
    hairdryer:
    mouse:
    toaster:
    hydrant:
    chair:
    laptop:
    book:
    backpack:
    cellphone: # from cellphone on, no zsp categories
    microwave:
    bench:
    bottle:
    couch:
    cup:
    suitcase:
    tv: