# @package _global_

co3d_refs:
  ref_name: 'r3'
  microwave: '410_55797_108431'
  hydrant: '250_26749_52968'
  toyplane: '104_12351_22036'
  toytruck: '372_41242_82218'
  bicycle: '136_15656_31168'
  cup: '31_1348_4176'
  remote: '107_12765_24738'
  backpack: '20_778_1839'
  mouse: '148_16485_31743'
  motorcycle: '365_39243_76541'
  tv: '48_2757_8246'
  car: '206_21810_45890'
  cellphone: '256_27642_53551'
  toybus: '404_53714_104744'
  toilet: '243_25922_52284'
  suitcase: '188_20344_38306'
  toaster: '274_29396_57830'
  hairdryer: '31_1294_3987'
  couch: '193_20841_43356'
  handbag: '396_49367_97469'
  book: '119_13955_27877'
  keyboard: '122_14256_27376'
  laptop: '112_13269_22712'
  toytrain: '255_27498_54620'
  bottle: '40_1835_5580'
  teddybear: '187_20219_38873'
  bench: '206_21811_45891'
  chair: '127_14751_30004'

checkpoints_cats_run_name:
  bicycle: 10-29_16-22-12_CO3D_NeMo_uni6d_dmtet1k_cat_def_bicycle_app0_r3_slurm
  train: 10-29_15-20-11_CO3D_NeMo_uni6d_dmtet1k_cat_def_train_app0_r3_slurm
  car: 10-29_15-16-10_CO3D_NeMo_uni6d_dmtet1k_cat_def_car_app0_r3_slurm
  bus: 10-29_15-14-09_CO3D_NeMo_uni6d_dmtet1k_cat_def_bus_app0_r3_slurm
  motorcycle: 10-29_16-23-16_CO3D_NeMo_uni6d_dmtet1k_cat_def_motorcycle_app0_r3_slurm
  airplane: 10-29_15-15-10_CO3D_NeMo_uni6d_dmtet1k_cat_def_airplane_app0_r3_slurm
  chair: 10-29_15-19-10_CO3D_NeMo_uni6d_dmtet1k_cat_def_chair_app0_r3_slurm
  bottle: 10-29_15-18-10_CO3D_NeMo_uni6d_dmtet1k_cat_def_bottle_app0_r3_slurm
  couch: 10-29_15-21-10_CO3D_NeMo_uni6d_dmtet1k_cat_def_couch_app0_r3_slurm
  tv: 10-29_15-17-11_CO3D_NeMo_uni6d_dmtet1k_cat_def_tv_app0_r3_slurm
  backpack: 11-03_18-26-03_CO3D_NeMo_dmtet1k_backpack_app0_r3_slurm
  bench: 11-03_18-25-12_CO3D_NeMo_dmtet1k_bench_app0_r3_slurm
  book: 11-03_18-24-21_CO3D_NeMo_dmtet1k_book_app0_r3_slurm
  cellphone: 11-03_18-29-46_CO3D_NeMo_dmtet1k_cellphone_app0_r3_slurm
  cup: 11-03_18-30-36_CO3D_NeMo_dmtet1k_cup_app0_r3_slurm
  hairdryer: 11-03_18-28-54_CO3D_NeMo_dmtet1k_hairdryer_app0_r3_slurm
  handbag: 11-03_18-28-04_CO3D_NeMo_dmtet1k_handbag_app0_r3_slurm
  hydrant: 11-04_12-32-43_CO3D_NeMo_dmtet1k_hydrant_app0_r3_slurm
  keyboard: 11-04_12-33-34_CO3D_NeMo_dmtet1k_keyboard_app0_r3_slurm
  laptop: 11-04_12-52-48_CO3D_NeMo_dmtet1k_laptop_app0_r3_slurm
  microwave: 11-12_23-07-49_CO3D_NeMo_dmtet1k_microwave_app0_r3_slurm # 11-06_09-44-20_CO3D_NeMo_dmtet1k_microwave_app0_r3_slurm
  mouse: 11-04_18-48-48_CO3D_NeMo_dmtet1k_mouse_app0_r3_slurm
  remote: 11-04_18-52-23_CO3D_NeMo_dmtet1k_remote_app0_r3_slurm
  suitcase: 11-04_18-51-32_CO3D_NeMo_dmtet1k_suitcase_app0_r3_slurm
  teddybear: 11-04_18-50-42_CO3D_NeMo_dmtet1k_teddybear_app0_r3_slurm
  toaster: 11-04_22-54-15_CO3D_NeMo_dmtet1k_toaster_app0_r3_slurm
  toilet: 11-04_22-55-06_CO3D_NeMo_dmtet1k_toilet_app0_r3_slurm
  truck: 11-04_22-55-56_CO3D_NeMo_dmtet1k_truck_app0_r3_slurm

checkpoints_cats:
  bicycle: ${platform.path_exps}/${checkpoints_cats_run_name.bicycle}/nemo.ckpt
  truck: ${platform.path_exps}/${checkpoints_cats_run_name.truck}/nemo.ckpt
  train: ${platform.path_exps}/${checkpoints_cats_run_name.train}/nemo.ckpt
  teddybear: ${platform.path_exps}/${checkpoints_cats_run_name.teddybear}/nemo.ckpt
  car: ${platform.path_exps}/${checkpoints_cats_run_name.car}/nemo.ckpt
  bus: ${platform.path_exps}/${checkpoints_cats_run_name.bus}/nemo.ckpt
  motorcycle: ${platform.path_exps}/${checkpoints_cats_run_name.motorcycle}/nemo.ckpt
  keyboard: ${platform.path_exps}/${checkpoints_cats_run_name.keyboard}/nemo.ckpt
  handbag: ${platform.path_exps}/${checkpoints_cats_run_name.handbag}/nemo.ckpt
  remote: ${platform.path_exps}/${checkpoints_cats_run_name.remote}/nemo.ckpt
  airplane: ${platform.path_exps}/${checkpoints_cats_run_name.airplane}/nemo.ckpt
  toilet: ${platform.path_exps}/${checkpoints_cats_run_name.toilet}/nemo.ckpt
  hairdryer: ${platform.path_exps}/${checkpoints_cats_run_name.hairdryer}/nemo.ckpt
  mouse: ${platform.path_exps}/${checkpoints_cats_run_name.mouse}/nemo.ckpt
  toaster: ${platform.path_exps}/${checkpoints_cats_run_name.toaster}/nemo.ckpt
  hydrant: ${platform.path_exps}/${checkpoints_cats_run_name.hydrant}/nemo.ckpt
  chair: ${platform.path_exps}/${checkpoints_cats_run_name.chair}/nemo.ckpt
  laptop: ${platform.path_exps}/${checkpoints_cats_run_name.laptop}/nemo.ckpt
  microwave: ${platform.path_exps}/${checkpoints_cats_run_name.microwave}/nemo.ckpt
  book: ${platform.path_exps}/${checkpoints_cats_run_name.book}/nemo.ckpt
  backpack: ${platform.path_exps}/${checkpoints_cats_run_name.backpack}/nemo.ckpt
  cellphone: ${platform.path_exps}/${checkpoints_cats_run_name.cellphone}/nemo.ckpt # from cellphone on, no zsp categories
  bench: ${platform.path_exps}/${checkpoints_cats_run_name.bench}/nemo.ckpt
  bottle: ${platform.path_exps}/${checkpoints_cats_run_name.bottle}/nemo.ckpt
  couch: ${platform.path_exps}/${checkpoints_cats_run_name.couch}/nemo.ckpt
  cup: ${platform.path_exps}/${checkpoints_cats_run_name.cup}/nemo.ckpt
  suitcase: ${platform.path_exps}/${checkpoints_cats_run_name.suitcase}/nemo.ckpt
  tv: ${platform.path_exps}/${checkpoints_cats_run_name.tv}/nemo.ckpt