defaults:
  - slurm_tf

partition: tflmb_gpu-1080 # alldlc_gpu-rtx2080 # lmb_gpu-rtx2080 # lmb_gpu-teslaP100 lmb_gpu-1080ti, lmb_gpu-rtx2080, testdlc_gpu-rtx2080, alldlc_gpu-rtx3080, alldlc_gpu-rtx2080, lmbdlc_gpu-rtx2080
# 1. lmb_gpu-rtx2080 : usually empty, only 3 slots
# 2. lmbdlc_gpu-rtx2080 : often pending (but eventually it will work)
# 3. alldlc_gpu-rtx3080 : usually empty (actually not anymore), but fewer gb?
# 4. alldlc_gpu-rtx2080 : biggest cluster
# 5. tflmb_gpu-rtx3090: lmb gpu (debugging)
# 6. tflmb_gpu-1080ti: lmb gpu (debugging)
# tflmb_gpu-rtx3090
# tflmb_gpu-1080ti