# @package _global_

co3d_refs:
  ref_name: 'r2'
  microwave: '422_58682_113779'
  hydrant: '206_21797_45640'
  toyplane: '372_41134_81910'
  toytruck: '190_20481_38360'
  bicycle: '373_41715_83384'
  cup: '31_1352_4179'
  remote: '100_11550_20470'
  backpack: '208_21991_45347'
  mouse: '195_21009_42771'
  motorcycle: '365_39206_76366'
  tv: '397_49994_98417'
  car: '194_20900_41097'
  cellphone: '173_18782_33853'
  toybus: '396_49702_97897'
  toilet: '115_13559_29303'
  suitcase: '353_37359_70296'
  toaster: '163_17890_33318'
  hairdryer: '28_930_2081'
  couch: '193_20852_43384'
  handbag: '396_49759_97999'
  book: '119_13954_28116'
  keyboard: '153_16977_32093'
  laptop: '274_29380_56806'
  toytrain: '190_20479_37788'
  bottle: '38_1661_5028'
  teddybear: '208_22018_45660'
  bench: '194_20884_40057'
  chair: '196_21091_41396'

checkpoints_cats_run_name:
  bicycle: 10-31_20-36-10_CO3D_NeMo_bicycle_r2_sparse_slurm
  train: 11-01_08-55-51_CO3D_NeMo_train_r2_sparse_slurm
  car: 10-31_20-14-16_CO3D_NeMo_car_r2_sparse_slurm
  bus: 10-31_20-12-14_CO3D_NeMo_bus_r2_sparse_slurm
  motorcycle: 10-31_20-37-11_CO3D_NeMo_motorcycle_r2_sparse_slurm
  airplane: 10-31_20-13-14_CO3D_NeMo_airplane_r2_sparse_slurm
  chair: 10-31_20-17-20_CO3D_NeMo_chair_r2_sparse_slurm
  bottle: 10-31_20-16-19_CO3D_NeMo_bottle_r2_sparse_slurm
  couch: 10-31_20-19-22_CO3D_NeMo_couch_r2_sparse_slurm
  tv: 11-01_08-55-14_CO3D_NeMo_tv_r2_sparse_slurm
  backpack: 11-10_14-24-22_CO3D_NeMo_backpack_r2_sparse_slurm
  bench: 11-10_13-10-55_CO3D_NeMo_bench_r2_sparse_slurm
  book: 11-10_14-18-11_CO3D_NeMo_book_r2_sparse_slurm
  cellphone: 11-10_13-08-51_CO3D_NeMo_cellphone_r2_sparse_slurm
  cup: 11-10_14-21-17_CO3D_NeMo_cup_r2_sparse_slurm
  hairdryer: 11-10_14-23-21_CO3D_NeMo_hairdryer_r2_sparse_slurm
  handbag: 11-10_14-20-15_CO3D_NeMo_handbag_r2_sparse_slurm
  hydrant: 11-10_15-26-27_CO3D_NeMo_hydrant_r2_sparse_slurm
  keyboard: 11-10_13-11-57_CO3D_NeMo_keyboard_r2_sparse_slurm
  laptop: 11-10_13-09-53_CO3D_NeMo_laptop_r2_sparse_slurm
  microwave: 11-10_13-16-04_CO3D_NeMo_microwave_r2_sparse_slurm
  mouse: 11-10_15-25-25_CO3D_NeMo_mouse_r2_sparse_slurm
  remote: 11-10_13-15-02_CO3D_NeMo_remote_r2_sparse_slurm
  suitcase: 11-10_14-19-13_CO3D_NeMo_suitcase_r2_sparse_slurm
  teddybear: 11-10_14-22-19_CO3D_NeMo_teddybear_r2_sparse_slurm
  toaster: 11-10_13-12-59_CO3D_NeMo_toaster_r2_sparse_slurm
  toilet: 11-10_13-14-01_CO3D_NeMo_toilet_r2_sparse_slurm
  truck: 11-10_14-17-09_CO3D_NeMo_truck_r2_sparse_slurm

checkpoints_cats:
  bicycle: ${platform.path_exps}/${checkpoints_cats_run_name.bicycle}/nemo.ckpt
  truck: ${platform.path_exps}/${checkpoints_cats_run_name.truck}/nemo.ckpt
  train: ${platform.path_exps}/${checkpoints_cats_run_name.train}/nemo.ckpt
  teddybear: ${platform.path_exps}/${checkpoints_cats_run_name.teddybear}/nemo.ckpt
  car: ${platform.path_exps}/${checkpoints_cats_run_name.car}/nemo.ckpt
  bus: ${platform.path_exps}/${checkpoints_cats_run_name.bus}/nemo.ckpt
  motorcycle: ${platform.path_exps}/${checkpoints_cats_run_name.motorcycle}/nemo.ckpt
  keyboard: ${platform.path_exps}/${checkpoints_cats_run_name.keyboard}/nemo.ckpt
  handbag: ${platform.path_exps}/${checkpoints_cats_run_name.handbag}/nemo.ckpt
  remote: ${platform.path_exps}/${checkpoints_cats_run_name.remote}/nemo.ckpt
  airplane: ${platform.path_exps}/${checkpoints_cats_run_name.airplane}/nemo.ckpt
  toilet: ${platform.path_exps}/${checkpoints_cats_run_name.toilet}/nemo.ckpt
  hairdryer: ${platform.path_exps}/${checkpoints_cats_run_name.hairdryer}/nemo.ckpt
  mouse: ${platform.path_exps}/${checkpoints_cats_run_name.mouse}/nemo.ckpt
  toaster: ${platform.path_exps}/${checkpoints_cats_run_name.toaster}/nemo.ckpt
  hydrant: ${platform.path_exps}/${checkpoints_cats_run_name.hydrant}/nemo.ckpt
  chair: ${platform.path_exps}/${checkpoints_cats_run_name.chair}/nemo.ckpt
  laptop: ${platform.path_exps}/${checkpoints_cats_run_name.laptop}/nemo.ckpt
  microwave: ${platform.path_exps}/${checkpoints_cats_run_name.microwave}/nemo.ckpt
  book: ${platform.path_exps}/${checkpoints_cats_run_name.book}/nemo.ckpt
  backpack: ${platform.path_exps}/${checkpoints_cats_run_name.backpack}/nemo.ckpt
  cellphone: ${platform.path_exps}/${checkpoints_cats_run_name.cellphone}/nemo.ckpt # from cellphone on, no zsp categories
  bench: ${platform.path_exps}/${checkpoints_cats_run_name.bench}/nemo.ckpt
  bottle: ${platform.path_exps}/${checkpoints_cats_run_name.bottle}/nemo.ckpt
  couch: ${platform.path_exps}/${checkpoints_cats_run_name.couch}/nemo.ckpt
  cup: ${platform.path_exps}/${checkpoints_cats_run_name.cup}/nemo.ckpt
  suitcase: ${platform.path_exps}/${checkpoints_cats_run_name.suitcase}/nemo.ckpt
  tv: ${platform.path_exps}/${checkpoints_cats_run_name.tv}/nemo.ckpt
