# @package _global_

checkpoint: ${checkpoint_opt}

checkpoints_refs_cats_run_name:
  r0:
    bicycle: 10-31_20-36-22_CO3D_NeMo_bicycle_r0_sparse_slurm
    train: 10-31_20-18-33_CO3D_NeMo_train_r0_sparse_slurm
    car: 10-31_20-14-28_CO3D_NeMo_car_r0_sparse_slurm
    bus: 11-01_08-54-49_CO3D_NeMo_bus_r0_sparse_slurm
    motorcycle: 10-31_20-37-23_CO3D_NeMo_motorcycle_r0_sparse_slurm
    airplane: 10-31_20-13-27_CO3D_NeMo_airplane_r0_sparse_slurm
    chair: 10-31_20-17-32_CO3D_NeMo_chair_r0_sparse_slurm
    bottle: 10-31_20-16-31_CO3D_NeMo_bottle_r0_sparse_slurm
    couch: 10-31_20-19-34_CO3D_NeMo_couch_r0_sparse_slurm
    tv: 10-31_20-15-30_CO3D_NeMo_tv_r0_sparse_slurm
    backpack: 11-10_14-24-35_CO3D_NeMo_backpack_r0_sparse_slurm
    bench: 11-10_13-11-07_CO3D_NeMo_bench_r0_sparse_slurm
    book: 11-10_14-18-23_CO3D_NeMo_book_r0_sparse_slurm
    cellphone: 11-10_13-09-04_CO3D_NeMo_cellphone_r0_sparse_slurm
    cup: 11-10_14-21-29_CO3D_NeMo_cup_r0_sparse_slurm
    hairdryer: 11-10_14-23-33_CO3D_NeMo_hairdryer_r0_sparse_slurm
    handbag: 11-10_14-20-27_CO3D_NeMo_handbag_r0_sparse_slurm
    hydrant: 11-10_15-26-39_CO3D_NeMo_hydrant_r0_sparse_slurm
    keyboard: 11-10_13-12-10_CO3D_NeMo_keyboard_r0_sparse_slurm
    laptop: 11-10_13-10-05_CO3D_NeMo_laptop_r0_sparse_slurm
    microwave: 11-10_13-16-17_CO3D_NeMo_microwave_r0_sparse_slurm
    mouse: 11-10_15-25-37_CO3D_NeMo_mouse_r0_sparse_slurm
    remote: 11-10_13-15-15_CO3D_NeMo_remote_r0_sparse_slurm
    suitcase: 11-10_14-19-26_CO3D_NeMo_suitcase_r0_sparse_slurm
    teddybear: 11-10_14-22-31_CO3D_NeMo_teddybear_r0_sparse_slurm
    toaster: 11-10_13-13-11_CO3D_NeMo_toaster_r0_sparse_slurm
    toilet: 11-10_13-14-13_CO3D_NeMo_toilet_r0_sparse_slurm
    truck: 11-10_14-17-21_CO3D_NeMo_truck_r0_sparse_slurm
  r1:
    bicycle: 10-31_20-35-33_CO3D_NeMo_bicycle_r1_sparse_slurm
    train: 10-31_20-17-45_CO3D_NeMo_train_r1_sparse_slurm
    car: 10-31_20-13-39_CO3D_NeMo_car_r1_sparse_slurm
    bus: 10-31_20-11-37_CO3D_NeMo_bus_r1_sparse_slurm
    motorcycle: 10-31_20-36-34_CO3D_NeMo_motorcycle_r1_sparse_slurm
    airplane: 10-31_20-12-38_CO3D_NeMo_airplane_r1_sparse_slurm
    chair: 10-31_20-16-43_CO3D_NeMo_chair_r1_sparse_slurm
    bottle: 10-31_20-15-42_CO3D_NeMo_bottle_r1_sparse_slurm
    couch: 10-31_20-18-45_CO3D_NeMo_couch_r1_sparse_slurm
    tv: 10-31_20-14-40_CO3D_NeMo_tv_r1_sparse_slurm
    backpack: 11-10_14-23-45_CO3D_NeMo_backpack_r1_sparse_slurm
    bench: 11-10_13-10-18_CO3D_NeMo_bench_r1_sparse_slurm
    book: 11-10_14-17-34_CO3D_NeMo_book_r1_sparse_slurm
    cellphone: 11-10_13-08-14_CO3D_NeMo_cellphone_r1_sparse_slurm
    cup: 11-10_14-20-40_CO3D_NeMo_cup_r1_sparse_slurm
    hairdryer: 11-10_14-22-43_CO3D_NeMo_hairdryer_r1_sparse_slurm
    handbag: 11-10_14-19-38_CO3D_NeMo_handbag_r1_sparse_slurm
    hydrant: 11-10_15-25-50_CO3D_NeMo_hydrant_r1_sparse_slurm
    keyboard: 11-10_13-11-20_CO3D_NeMo_keyboard_r1_sparse_slurm
    laptop: 11-10_13-09-16_CO3D_NeMo_laptop_r1_sparse_slurm
    microwave: 11-10_13-15-27_CO3D_NeMo_microwave_r1_sparse_slurm
    mouse: 11-10_15-24-47_CO3D_NeMo_mouse_r1_sparse_slurm
    remote: 11-10_13-14-25_CO3D_NeMo_remote_r1_sparse_slurm
    suitcase: 11-10_14-18-36_CO3D_NeMo_suitcase_r1_sparse_slurm
    teddybear: 11-10_14-21-42_CO3D_NeMo_teddybear_r1_sparse_slurm
    toaster: 11-10_13-12-22_CO3D_NeMo_toaster_r1_sparse_slurm
    toilet: 11-10_13-13-23_CO3D_NeMo_toilet_r1_sparse_slurm
    truck: 11-10_14-16-29_CO3D_NeMo_truck_r1_sparse_slurm
  r2:
    bicycle: 10-31_20-36-10_CO3D_NeMo_bicycle_r2_sparse_slurm
    train: 11-01_08-55-51_CO3D_NeMo_train_r2_sparse_slurm
    car: 10-31_20-14-16_CO3D_NeMo_car_r2_sparse_slurm
    bus: 10-31_20-12-14_CO3D_NeMo_bus_r2_sparse_slurm
    motorcycle: 10-31_20-37-11_CO3D_NeMo_motorcycle_r2_sparse_slurm
    airplane: 10-31_20-13-14_CO3D_NeMo_airplane_r2_sparse_slurm
    chair: 10-31_20-17-20_CO3D_NeMo_chair_r2_sparse_slurm
    bottle: 10-31_20-16-19_CO3D_NeMo_bottle_r2_sparse_slurm
    couch: 10-31_20-19-22_CO3D_NeMo_couch_r2_sparse_slurm
    tv: 11-01_08-55-14_CO3D_NeMo_tv_r2_sparse_slurm
    backpack: 11-10_14-24-22_CO3D_NeMo_backpack_r2_sparse_slurm
    bench: 11-10_13-10-55_CO3D_NeMo_bench_r2_sparse_slurm
    book: 11-10_14-18-11_CO3D_NeMo_book_r2_sparse_slurm
    cellphone: 11-10_13-08-51_CO3D_NeMo_cellphone_r2_sparse_slurm
    cup: 11-10_14-21-17_CO3D_NeMo_cup_r2_sparse_slurm
    hairdryer: 11-10_14-23-21_CO3D_NeMo_hairdryer_r2_sparse_slurm
    handbag: 11-10_14-20-15_CO3D_NeMo_handbag_r2_sparse_slurm
    hydrant: 11-10_15-26-27_CO3D_NeMo_hydrant_r2_sparse_slurm
    keyboard: 11-10_13-11-57_CO3D_NeMo_keyboard_r2_sparse_slurm
    laptop: 11-10_13-09-53_CO3D_NeMo_laptop_r2_sparse_slurm
    microwave: 11-10_13-16-04_CO3D_NeMo_microwave_r2_sparse_slurm
    mouse: 11-10_15-25-25_CO3D_NeMo_mouse_r2_sparse_slurm
    remote: 11-10_13-15-02_CO3D_NeMo_remote_r2_sparse_slurm
    suitcase: 11-10_14-19-13_CO3D_NeMo_suitcase_r2_sparse_slurm
    teddybear: 11-10_14-22-19_CO3D_NeMo_teddybear_r2_sparse_slurm
    toaster: 11-10_13-12-59_CO3D_NeMo_toaster_r2_sparse_slurm
    toilet: 11-10_13-14-01_CO3D_NeMo_toilet_r2_sparse_slurm
    truck: 11-10_14-17-09_CO3D_NeMo_truck_r2_sparse_slurm
  r3:
    bicycle: 10-31_20-35-45_CO3D_NeMo_bicycle_r3_sparse_slurm
    train: 10-31_20-17-57_CO3D_NeMo_train_r3_sparse_slurm
    car: 11-01_08-55-02_CO3D_NeMo_car_r3_sparse_slurm
    bus: 10-31_20-11-49_CO3D_NeMo_bus_r3_sparse_slurm
    motorcycle: 10-31_20-36-46_CO3D_NeMo_motorcycle_r3_sparse_slurm
    airplane: 10-31_20-12-50_CO3D_NeMo_airplane_r3_sparse_slurm
    chair: 10-31_20-16-55_CO3D_NeMo_chair_r3_sparse_slurm
    bottle: 11-01_08-55-27_CO3D_NeMo_bottle_r3_sparse_slurm
    couch: 10-31_20-18-58_CO3D_NeMo_couch_r3_sparse_slurm
    tv: 10-31_20-14-52_CO3D_NeMo_tv_r3_sparse_slurm
    backpack: 11-10_14-23-58_CO3D_NeMo_backpack_r3_sparse_slurm
    bench: 11-10_13-10-30_CO3D_NeMo_bench_r3_sparse_slurm
    book: 11-11_19-24-05_CO3D_NeMo_book_r3_sparse_slurm
    cellphone: 11-10_13-08-27_CO3D_NeMo_cellphone_r3_sparse_slurm
    cup: 11-10_14-20-52_CO3D_NeMo_cup_r3_sparse_slurm
    hairdryer: 11-10_14-22-56_CO3D_NeMo_hairdryer_r3_sparse_slurm
    handbag: 11-10_14-19-50_CO3D_NeMo_handbag_r3_sparse_slurm
    hydrant: 11-10_15-26-02_CO3D_NeMo_hydrant_r3_sparse_slurm
    keyboard: 11-10_13-11-32_CO3D_NeMo_keyboard_r3_sparse_slurm
    laptop: 11-10_13-09-28_CO3D_NeMo_laptop_r3_sparse_slurm
    microwave: 11-10_13-15-40_CO3D_NeMo_microwave_r3_sparse_slurm
    mouse: 11-10_15-25-00_CO3D_NeMo_mouse_r3_sparse_slurm
    remote: 11-10_13-14-38_CO3D_NeMo_remote_r3_sparse_slurm
    suitcase: 11-10_14-18-48_CO3D_NeMo_suitcase_r3_sparse_slurm
    teddybear: 11-10_14-21-54_CO3D_NeMo_teddybear_r3_sparse_slurm
    toaster: 11-10_13-12-34_CO3D_NeMo_toaster_r3_sparse_slurm
    toilet: 11-10_13-13-36_CO3D_NeMo_toilet_r3_sparse_slurm
    truck: 11-10_14-16-44_CO3D_NeMo_truck_r3_sparse_slurm
  r4:
    bicycle: 10-31_20-35-58_CO3D_NeMo_bicycle_r4_sparse_slurm
    train: 10-31_20-18-09_CO3D_NeMo_train_r4_sparse_slurm
    car: 10-31_20-14-04_CO3D_NeMo_car_r4_sparse_slurm
    bus: 10-31_20-12-01_CO3D_NeMo_bus_r4_sparse_slurm
    motorcycle: 10-31_20-36-59_CO3D_NeMo_motorcycle_r4_sparse_slurm
    airplane: 10-31_20-13-02_CO3D_NeMo_airplane_r4_sparse_slurm
    chair: 10-31_20-17-07_CO3D_NeMo_chair_r4_sparse_slurm
    bottle: 11-01_08-55-39_CO3D_NeMo_bottle_r4_sparse_slurm
    couch: 10-31_20-19-10_CO3D_NeMo_couch_r4_sparse_slurm
    tv: 10-31_20-15-04_CO3D_NeMo_tv_r4_sparse_slurm
    backpack: 11-10_14-24-10_CO3D_NeMo_backpack_r4_sparse_slurm
    bench: 11-10_13-10-42_CO3D_NeMo_bench_r4_sparse_slurm
    book: 11-10_14-17-59_CO3D_NeMo_book_r4_sparse_slurm
    cellphone: 11-10_13-08-39_CO3D_NeMo_cellphone_r4_sparse_slurm
    cup: 11-10_14-21-05_CO3D_NeMo_cup_r4_sparse_slurm
    hairdryer: 11-10_14-23-08_CO3D_NeMo_hairdryer_r4_sparse_slurm
    handbag: 11-10_14-20-03_CO3D_NeMo_handbag_r4_sparse_slurm
    hydrant: 11-10_15-26-14_CO3D_NeMo_hydrant_r4_sparse_slurm
    keyboard: 11-10_13-11-44_CO3D_NeMo_keyboard_r4_sparse_slurm
    laptop: 11-10_13-09-41_CO3D_NeMo_laptop_r4_sparse_slurm
    microwave: 11-10_13-15-52_CO3D_NeMo_microwave_r4_sparse_slurm
    mouse: 11-10_15-25-13_CO3D_NeMo_mouse_r4_sparse_slurm
    remote: 11-10_13-14-50_CO3D_NeMo_remote_r4_sparse_slurm
    suitcase: 11-10_14-19-01_CO3D_NeMo_suitcase_r4_sparse_slurm
    teddybear: 11-10_14-22-06_CO3D_NeMo_teddybear_r4_sparse_slurm
    toaster: 11-10_13-12-47_CO3D_NeMo_toaster_r4_sparse_slurm
    toilet: 11-10_13-13-48_CO3D_NeMo_toilet_r4_sparse_slurm
    truck: 11-10_14-16-57_CO3D_NeMo_truck_r4_sparse_slurm