defaults:
  - pascal3d

modalities:
    - 'rgb'
    - 'rgb_mask'
    - 'category'
    - 'category_id'
    - 'mask'
    - 'kpts2d_annot'
    - 'kpts2d_annot_vsbl'
    - 'kpts3d'
    - 'cam_intr4x4'
    - 'cam_tform4x4_obj'
    - 'size'
    - 'bbox'
    # - 'depth' # note: broken with nvidia-rasterizer
    - 'mesh'

preprocess:
  cuboid:
    enabled: True
    override: False
    remove_previous: False
  mask:
    enabled: True
    override: False
    remove_previous: False
  depth:
    enabled: False # note: broken with nvidia-rasterizer
    override: False
    remove_previous: False

name: pascal3d_occ_l2
class_name: Pascal3D_Occ

path_raw: ${platform.path_datasets_raw}/PASCAL3D_Occ
path_preprocess: ${platform.path_datasets_preprocess}/PASCAL3D_OccPreprocess

url_pascal3d_occ_script: https://raw.githubusercontent.com/Angtian/OccludedPASCAL3D/master/download_FG.sh

rpath_pascal3d_raw: PASCAL3D+_release1.1
path_pascal3d_raw: ${platform.path_datasets_raw}/${.rpath_pascal3d_raw}

dict_nested_frames:
     lvl2: