name: spair71k
class_name: SPair71K

modalities:
    - 'rgbs'
    #- 'rgb_mask'
    - 'category'
    - 'category_id'
    #- 'mask'
    #- 'kpts2d_annot_vsbl'
    #- 'kpts3d'
    - 'kpts2d_annots'
    - 'kpts2d_annots_ids'
    - 'cam_intr4x4s'
    - 'cam_tform4x4_objs'
    - 'sizes'
    - 'bboxs'
    #- 'depth'
    #- 'mesh'

subset_fraction: 0.1 #0.05

url_spair71k_raw: http://cvlab.postech.ac.kr/research/SPair-71k/data/SPair-71k.tar.gz
rpath_spair71k_raw: SPair71K

rpath_pascal3d_raw: PASCAL3D+_release1.1
path_pascal3d_raw: ${platform.path_datasets_raw}/${.rpath_pascal3d_raw}

path_raw: ${platform.path_datasets_raw}/${.rpath_spair71k_raw}
path_preprocess: ${platform.path_datasets_preprocess}/SPair71K_Preprocess

setup:
  enabled: False
  override: False
  remove_previous: False

extract_meta:
  enabled: False
  override: False
  remove_previous: False

#preprocess:
#  cuboid:
#    enabled: True
#    override: False
#    remove_previous: False
#  mask:
#    enabled: True
#    override: False
#    remove_previous: False
#  depth:
#    enabled: True
#    override: False
#    remove_previous: False

image_sizes:
    aeroplane: [512, 512]
    bicycle: [512, 512]
    boat: [512, 512]
    bottle: [512, 512]
    bus: [512, 512]
    car: [512, 512]
    chair: [512, 512]
    diningtable: [512, 512]
    motorbike: [512, 512]
    train: [512, 512]
    tvmonitor: [512, 512]

# skipped due to zero distance
#   car:
#       n03770679_15832
#       n03770679_9715
#       n04037443_21947
#       n04037443_4668

categories:
   - aeroplane
   - bicycle
   - boat
   - bottle
   - bus
   - car
   - chair
   - diningtable
   - motorbike
   - train
   - tvmonitor

dict_nested_frames:
  test:
