#defaults:
#  - keypoints@keypoints

name: wild6d
class_name: WILD6D

modalities:
    - 'size'
    - 'category'
    - 'category_id'
    - 'cam_intr4x4'
    - 'cam_tform4x4_obj'
    #- 'rays_center3d'
    - 'category'
    - 'rgb'
    - 'rgb_mask'
    - 'mask'
    - 'sequence_name_unique'
    - 'sequence'
    - 'mesh'
#    - 'pcl'

# mesh_type: 'alpha500' # 'alpha500' 'cuboid500' 'cuboid500' 'convex500', 'voxel500' 'poisson500', 'alpha500', 'cuboid1000'
# tform_obj_type: 'label3d_cuboid' #'raw' 'label3d_cuboid' 'label3d_cuboid' 'aligned_N_alpha500_dinov2b/r0'

#mesh_feats_type: 'M_dinov2_vitb14_frozen_base_no_norm_T_centerzoom512_R_acc' # dinov2_vitb14_frozen_base_no_norm M_dinov2_frozen_base_T_centerzoom512_R_acc, M_nemo_old_T_centerzoom512_R_acc 'R_acc' # 'R_avg', 'R_avg_norm'

#mesh_feats_dist_reduce_type: 'min_avg' # 'avg', 'min', 'min_avg'

frames_count_max_per_sequence:
sequences_count_max_per_category:
block_negative_depth: False

path_raw: ${platform.path_datasets_raw}/WILD6D
path_preprocess: ${platform.path_datasets_raw}/WILD6D_Preprocess

setup:
  enabled: False
  override: False
  remove_previous: False

extract_meta:
  enabled: False
  override: False
  remove_previous: False

preprocess:
  sfm:
    enabled: True
    override: False
  mask:
    enabled: True
    override: False
  pcl:
    enabled: True
    override: False
  tform_obj:
    enabled: True
    override: False
  mesh:
    enabled: True
    override: False
  mesh_feats:
    enabled: False
    override: False
  mesh_feats_dist:
    enabled: False
    override: False

#dict_nested_frames_ban:

#dict_nested_frames:

categories:
#    - mug
#    - laptop
#    - camera
#    - bottle
#    - bowl
