defaults:
  - dinov2_frozen_base

backbone:
  class_name: DINOv2_Sph
  hub_repo: 'facebookresearch/dinov2' # 'facebookresearch/dino:main', 'facebookresearch/dinov2'
  hub_model: 'dinov2_vitb14' # dino_vits8, dino_vitb8, dino_vits16, dino_vitb16, dinov2_vits14, dinov2_vitb14, dinov2_vitl14, dinov2_vitg14
  sph_weights: ${platform.path_exps}/weights/exp_002_in3d_wo_sym_and_co3d_200.pth