# @package _global_

co3d_refs:
  ref_name: 'r0'
  microwave: '404_53420_104078'
  hydrant: '185_19984_37720'
  toyplane: '111_13148_23780'
  toytruck: '240_25396_52241'
  bicycle: '354_37645_70054'
  cup: '34_1421_4329'
  remote: '195_21014_43617'
  backpack: '196_21139_44291'
  mouse: '14_189_1165'
  motorcycle: '349_36520_66801'
  tv: '398_50481_99038'
  car: '185_19982_37678'
  cellphone: '112_13284_23744'
  toybus: '199_21374_39988'
  toilet: '243_25916_51736'
  suitcase: '219_23131_48849'
  toaster: '274_29366_56609'
  hairdryer: '101_11750_20715'
  couch: '193_20843_43364'
  handbag: '396_49728_97942'
  book: '102_11962_21291'
  keyboard: '200_21526_41664'
  laptop: '131_15148_29934'
  toytrain: '346_36011_65893'
  bottle: '40_1834_5582'
  teddybear: '196_21096_41534'
  bench: '194_20936_42354'
  chair: '218_22993_47010'

checkpoints_cats_run_name:
  bicycle: 10-30_15-31-42_CO3D_NeMo_uni6d_dmtet1k_inst_def6d_coord_conv4_bicycle_r0_slurm
  train: 10-30_14-29-38_CO3D_NeMo_uni6d_dmtet1k_inst_def6d_coord_conv4_train_r0_slurm
  car: 10-30_15-43-35_CO3D_NeMo_uni6d_dmtet1k_inst_def6d_coord_conv4_car_r0_slurm
  bus: 10-30_15-41-33_CO3D_NeMo_uni6d_dmtet1k_inst_def6d_coord_conv4_bus_r0_slurm
  motorcycle: 10-30_15-32-48_CO3D_NeMo_uni6d_dmtet1k_inst_def6d_coord_conv4_motorcycle_r0_slurm
  airplane: 10-30_15-42-34_CO3D_NeMo_uni6d_dmtet1k_inst_def6d_coord_conv4_airplane_r0_slurm
  chair: 11-01_09-00-31_CO3D_NeMo_uni6d_dmtet1k_inst_def6d_coord_conv4_chair_r0_slurm
  bottle: 10-30_15-45-38_CO3D_NeMo_uni6d_dmtet1k_inst_def6d_coord_conv4_bottle_r0_slurm
  couch: 10-30_16-32-15_CO3D_NeMo_uni6d_dmtet1k_inst_def6d_coord_conv4_couch_r0_slurm
  tv: 11-01_08-59-42_CO3D_NeMo_uni6d_dmtet1k_inst_def6d_coord_conv4_tv_r0_slurm
  backpack: 11-09_20-03-11_CO3D_NeMo_uni6d_dmtet1k_inst_def6d_coord_conv4_backpack_r0_slurm
  bench: 11-09_18-49-53_CO3D_NeMo_uni6d_dmtet1k_inst_def6d_coord_conv4_bench_r0_slurm
  book: 11-09_19-57-04_CO3D_NeMo_uni6d_dmtet1k_inst_def6d_coord_conv4_book_r0_slurm
  cellphone: 11-09_18-47-47_CO3D_NeMo_uni6d_dmtet1k_inst_def6d_coord_conv4_cellphone_r0_slurm
  cup: 11-10_12-37-52_CO3D_NeMo_uni6d_dmtet1k_inst_def6d_coord_conv4_cup_r0_slurm
  hairdryer: 11-09_20-02-10_CO3D_NeMo_uni6d_dmtet1k_inst_def6d_coord_conv4_hairdryer_r0_slurm
  handbag: 11-09_19-59-06_CO3D_NeMo_uni6d_dmtet1k_inst_def6d_coord_conv4_handbag_r0_slurm
  hydrant: 11-09_21-05-15_CO3D_NeMo_uni6d_dmtet1k_inst_def6d_coord_conv4_hydrant_r0_slurm
  keyboard: 11-09_18-50-56_CO3D_NeMo_uni6d_dmtet1k_inst_def6d_coord_conv4_keyboard_r0_slurm
  laptop: 11-09_18-48-50_CO3D_NeMo_uni6d_dmtet1k_inst_def6d_coord_conv4_laptop_r0_slurm
  microwave: 11-13_08-26-12_CO3D_NeMo_uni6d_dmtet1k_inst_def6d_coord_conv4_microwave_r0_slurm # 11-09_18-55-02_CO3D_NeMo_uni6d_dmtet1k_inst_def6d_coord_conv4_microwave_r0_slurm
  mouse: 11-09_21-04-13_CO3D_NeMo_uni6d_dmtet1k_inst_def6d_coord_conv4_mouse_r0_slurm
  remote: 11-09_18-54-01_CO3D_NeMo_uni6d_dmtet1k_inst_def6d_coord_conv4_remote_r0_slurm
  suitcase: 11-10_12-37-03_CO3D_NeMo_uni6d_dmtet1k_inst_def6d_coord_conv4_suitcase_r0_slurm
  teddybear: 11-09_20-01-08_CO3D_NeMo_uni6d_dmtet1k_inst_def6d_coord_conv4_teddybear_r0_slurm
  toaster: 11-09_18-51-59_CO3D_NeMo_uni6d_dmtet1k_inst_def6d_coord_conv4_toaster_r0_slurm
  toilet: 11-09_18-53-00_CO3D_NeMo_uni6d_dmtet1k_inst_def6d_coord_conv4_toilet_r0_slurm
  truck: 11-09_19-56-03_CO3D_NeMo_uni6d_dmtet1k_inst_def6d_coord_conv4_truck_r0_slurm



checkpoints_cats:
  bicycle: ${platform.path_exps}/${checkpoints_cats_run_name.bicycle}/nemo.ckpt
  truck: ${platform.path_exps}/${checkpoints_cats_run_name.truck}/nemo.ckpt
  train: ${platform.path_exps}/${checkpoints_cats_run_name.train}/nemo.ckpt
  teddybear: ${platform.path_exps}/${checkpoints_cats_run_name.teddybear}/nemo.ckpt
  car: ${platform.path_exps}/${checkpoints_cats_run_name.car}/nemo.ckpt
  bus: ${platform.path_exps}/${checkpoints_cats_run_name.bus}/nemo.ckpt
  motorcycle: ${platform.path_exps}/${checkpoints_cats_run_name.motorcycle}/nemo.ckpt
  keyboard: ${platform.path_exps}/${checkpoints_cats_run_name.keyboard}/nemo.ckpt
  handbag: ${platform.path_exps}/${checkpoints_cats_run_name.handbag}/nemo.ckpt
  remote: ${platform.path_exps}/${checkpoints_cats_run_name.remote}/nemo.ckpt
  airplane: ${platform.path_exps}/${checkpoints_cats_run_name.airplane}/nemo.ckpt
  toilet: ${platform.path_exps}/${checkpoints_cats_run_name.toilet}/nemo.ckpt
  hairdryer: ${platform.path_exps}/${checkpoints_cats_run_name.hairdryer}/nemo.ckpt
  mouse: ${platform.path_exps}/${checkpoints_cats_run_name.mouse}/nemo.ckpt
  toaster: ${platform.path_exps}/${checkpoints_cats_run_name.toaster}/nemo.ckpt
  hydrant: ${platform.path_exps}/${checkpoints_cats_run_name.hydrant}/nemo.ckpt
  chair: ${platform.path_exps}/${checkpoints_cats_run_name.chair}/nemo.ckpt
  laptop: ${platform.path_exps}/${checkpoints_cats_run_name.laptop}/nemo.ckpt
  microwave: ${platform.path_exps}/${checkpoints_cats_run_name.microwave}/nemo.ckpt
  book: ${platform.path_exps}/${checkpoints_cats_run_name.book}/nemo.ckpt
  backpack: ${platform.path_exps}/${checkpoints_cats_run_name.backpack}/nemo.ckpt
  cellphone: ${platform.path_exps}/${checkpoints_cats_run_name.cellphone}/nemo.ckpt # from cellphone on, no zsp categories
  bench: ${platform.path_exps}/${checkpoints_cats_run_name.bench}/nemo.ckpt
  bottle: ${platform.path_exps}/${checkpoints_cats_run_name.bottle}/nemo.ckpt
  couch: ${platform.path_exps}/${checkpoints_cats_run_name.couch}/nemo.ckpt
  cup: ${platform.path_exps}/${checkpoints_cats_run_name.cup}/nemo.ckpt
  suitcase: ${platform.path_exps}/${checkpoints_cats_run_name.suitcase}/nemo.ckpt
  tv: ${platform.path_exps}/${checkpoints_cats_run_name.tv}/nemo.ckpt
